name: 'Cal\'s Work Command'
description: 'Does whatever Cal needs it to do at the moment'
author: 'Cal Evans'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check-circle'
  color: 'green'
